wandb_version: 1

activation:
  value: Mish
batch_size:
  value: 32
batchnorm:
  value: Y
dataug:
  value: N
dense_neurons:
  value: 64
dropout:
  value: 0.1
epochs:
  value: 10
filter_org:
  value: 2
filter_size:
  value: 3
img_size:
  value: 128
learning_rate:
  value: 0.001
num_filters:
  value: 64
optimizer:
  value: adam
padding:
  value: 1
stride:
  value: 1
usedropout:
  value: Y
