_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 41
                - 55
                - 106
            "2":
                - 1
                - 41
                - 55
                - 106
            "3":
                - 2
                - 14
                - 16
                - 17
                - 23
                - 55
            "4": 3.12.3
            "5": 0.19.8
            "8":
                - 5
            "12": 0.19.8
            "13": linux-x86_64
activation:
    value: Mish
batch_size:
    value: 32
batchnorm:
    value: "Y"
dataug:
    value: "N"
dense_neurons:
    value: 64
dropout:
    value: 0.1
epochs:
    value: 10
filter_org:
    value: 2
filter_size:
    value: 3
img_size:
    value: 64
learning_rate:
    value: 0.001
num_filters:
    value: 64
optimizer:
    value: adam
padding:
    value: 1
stride:
    value: 1
usedropout:
    value: "Y"
